/*
 * Copyright (c) 2019, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */
#include "region_defs.h"
#include "mcuboot_config/mcuboot_config.h"

#define _HEX(n) 0x##n
#define HEX(n)  _HEX(n)

/* Enumeration that is used by the assemble.py and imgtool\main.py scripts
 * for correct binary generation when nested macros are used
 */

enum image_attributes
{
  RE_BASE_ADDRESS_APP_S = BASE_ADDRESS_APP_S,
  RE_BASE_ADDRESS_APP_NS = BASE_ADDRESS_APP_NS,

  RE_FLASH_AREA_0_OFFSET = FLASH_AREA_0_OFFSET,
  RE_FLASH_AREA_1_OFFSET = FLASH_AREA_1_OFFSET,

  RE_FLASH_AREA_0_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_0_OFFSET,
  RE_FLASH_AREA_1_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_1_OFFSET,
  RE_FLASH_AREA_2_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_2_OFFSET,
  RE_FLASH_AREA_3_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_3_OFFSET,

  RE_FLASH_S_PARTITION_SIZE = FLASH_S_PARTITION_SIZE,
  RE_FLASH_NS_PARTITION_SIZE = FLASH_NS_PARTITION_SIZE,

#if (MCUBOOT_S_DATA_IMAGE_NUMBER == 1)
  RE_S_DATA_IMAGE_NUMBER = 1,
  RE_FLASH_AREA_6_OFFSET = FLASH_AREA_6_OFFSET,
  RE_FLASH_AREA_6_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_6_OFFSET,
#else
  RE_S_DATA_IMAGE_NUMBER = 0,
  RE_FLASH_AREA_6_OFFSET = 0,
  RE_FLASH_AREA_6_ADDRESS = 0,
#endif /* MCUBOOT_S_DATA_IMAGE_NUMBER == 1 */

#if (MCUBOOT_NS_DATA_IMAGE_NUMBER == 1)
  RE_NS_DATA_IMAGE_NUMBER = 1,
  RE_FLASH_AREA_7_OFFSET = FLASH_AREA_7_OFFSET,
  RE_FLASH_AREA_7_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_7_OFFSET,
#else
  RE_NS_DATA_IMAGE_NUMBER = 0,
  RE_FLASH_AREA_7_OFFSET = 0,
  RE_FLASH_AREA_7_ADDRESS = 0,
#endif /* MCUBOOT_S_DATA_IMAGE_NUMBER == 1 */
};
